version: '3.1'
services:
    mariadb:
        image: 'mariadb:11.0'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=acme
        ports:
            - '11003:3306'

    postgres:
        image: 'postgres:15-alpine'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=postgres
        ports:
            - '11004:5432'

    php-fpm:
        build: .
        working_dir: /application
        volumes:
            - '.:/application'

    mongodb:
        image: mongo:5
        ports:
            - '27017:27017'
