name: 🔎 QA

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: 🧹 PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Delete composer files to avoid installing dependencies
        run: rm -v composer.json

      - name: PHP-CS-Fixer
        uses: docker://jakzal/phpqa:1.113.8-php8.4-alpine
        with:
          args: php-cs-fixer --config=./.qa/.php-cs-fixer.dist.php --dry-run --diff --no-interaction --ansi fix --show-progress none

  php-stan:
    name: 🔎 PHPStan
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v5

      # the Docker image will install the dependencies automatically

      -   name: ✅ PHPStan
          uses: docker://jakzal/phpqa:1.111-php8.3-alpine
          env:
              COMPOSER_IGNORE_PLATFORM_REQ: ext-mongodb
              # this will hide the output of the automatic call to `composer install`
              SHELL_VERBOSITY: -1
          with:
              # `SHELL_VERBOSITY=0` will restore the default verbosity, so that PHPStan output the results
              args: sh -c "SHELL_VERBOSITY=0 phpstan analyse --configuration ./.qa/phpstan.neon --no-progress"

  composer-validate:
    name: 🎵 Composer validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: ✅ Composer validate
        run: composer validate --strict
